
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 34;
  public static final int MULT = 24;
  public static final int PERIOD = 33;
  public static final int LPAREN = 29;
  public static final int INT = 9;
  public static final int PRINTLN = 19;
  public static final int LESS = 28;
  public static final int MINUS = 23;
  public static final int STATIC = 4;
  public static final int RPAREN = 30;
  public static final int NOT = 27;
  public static final int SEMICOLON = 31;
  public static final int AND = 26;
  public static final int COMMA = 32;
  public static final int CLASS = 5;
  public static final int PLUS = 22;
  public static final int MAIN = 6;
  public static final int IF = 12;
  public static final int THIS = 20;
  public static final int EOF = 0;
  public static final int BOOLEAN = 10;
  public static final int RETURN = 8;
  public static final int RBRACKET = 35;
  public static final int TRUE = 17;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int BECOMES = 25;
  public static final int VOID = 7;
  public static final int LBRACE = 36;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int RBRACE = 37;
  public static final int EXTENDS = 16;
  public static final int STRING = 11;
  public static final int FALSE = 18;
  public static final int LENGTH = 15;
  public static final int INTEGER_LITERAL = 39;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "PUBLIC",
  "STATIC",
  "CLASS",
  "MAIN",
  "VOID",
  "RETURN",
  "INT",
  "BOOLEAN",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "LENGTH",
  "EXTENDS",
  "TRUE",
  "FALSE",
  "PRINTLN",
  "THIS",
  "NEW",
  "PLUS",
  "MINUS",
  "MULT",
  "BECOMES",
  "AND",
  "NOT",
  "LESS",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "PERIOD",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "IDENTIFIER",
  "INTEGER_LITERAL"
  };
}

